---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: http-echo
  name: http-echo
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: http-echo_mapping
      grpc: false
      prefix: /echo
      rewrite: /
      service: http-echo
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http-echo
    targetPort: http
  selector:
    service: http-echo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http-echo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: http-echo
    spec:
      containers:
      - name: http-echo
        image: solsson/http-echo
        env:
        - name: PORT
          value: "80"
        ports:
        - name: http
          containerPort: 80
      restartPolicy: Always